version: "v1"
services:
  todo-redis:
    container_name: todo-redis
    image: redis:5.0.3
    ports:
      -6379:6379
  todo-postgres:
    container_name: todo-postgres
    image: postgres:11.2
    ports:
      -5432:5432
    environment:
      - POSTGRES_DATABASE=todo
      - POSTGRES_USER=todo
      - POSTGRES_PASS=todo1234
  todo-elastic:
    container_name: todo-api
    image: elasticsearch:6.6.1
    ports:
      -9200:9200
      -9300:9300
    environment:
      - discovery.type=single-node
  todo-api:
    container_name: todo-api
    image: todo-api:1.0
    ports:
      -3000:3000
    environment:
      - POSTGRES_HOST=todo-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=todo
      - POSTGRES_USER=todo
      - POSTGRES_PASS=todo1234
      - REDIS_HOST=todo-redis
      - REDIS_PORT=6379
      - ELASTIC_HOST=todo-elastic
      - ELASTICSEARCH_PORT=9200
    volumes:
      - /app/node_modules
    depends_on:
      - todo-api
  todo-view:
    container_name: todo-view
    image: todo-view:1.0
    ports:
      -4200:4200
    volumes:
      -${pwd}/todo-view:/usr/src/app
      -/usr/src/app/node_modules
    depends_on:
      - todo-api

  todo-proxy:
    container_name: todo-proxy
    image: todo-proxy:1.0
    ports:
      - 8080:80
    depends_on:
      - todo-api
      - todo-view